// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyHubAPI.Data;

#nullable disable

namespace StudyHubAPI.Migrations
{
    [DbContext(typeof(StudyHubDbContext))]
    [Migration("20260826170305_AddRefreshTokensTable")]
    partial class AddRefreshTokensTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudyHubAPI.Models.Entities.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.HasKey("PersonID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Person", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Person_Role", "[Role] BETWEEN 1 AND 3");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.Reservations", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("ReservationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<byte>("ReservationStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DATETIME");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("DECIMAL(6,2)");

                    b.Property<int>("WorkspaceID")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("AdminID");

                    b.HasIndex("CustomerID")
                        .HasDatabaseName("IX_Reservations_CustomerID");

                    b.HasIndex("WorkspaceID")
                        .HasDatabaseName("IX_Reservations_WorkspaceID");

                    b.ToTable("Reservations", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Reservations_ActualDates", "[ActualStartDate] IS NULL OR [ActualEndDate] IS NULL OR [ActualEndDate] >= [ActualStartDate]");

                            t.HasCheckConstraint("CHK_Reservations_DateRange", "[EndDate] > [StartDate]");

                            t.HasCheckConstraint("CHK_Reservations_Status", "[ReservationStatus] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CHK_Reservations_TotalAmount", "[TotalAmount] >= 0");
                        });
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.Reviews", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Rate")
                        .HasColumnType("tinyint");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("ReservationID")
                        .HasDatabaseName("IX_Reviews_ReservationID");

                    b.ToTable("Reviews", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Reviews_Rate", "[Rate] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.Workspaces", b =>
                {
                    b.Property<int>("WorkspaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkspaceID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<int>("MaximumCapacity")
                        .HasColumnType("int");

                    b.Property<byte>("WorkspaceStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("WorkspaceID");

                    b.ToTable("Workspaces", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Workspaces_HourlyRate", "[HourlyRate] > 0");

                            t.HasCheckConstraint("CHK_Workspaces_MaximumCapacity", "[MaximumCapacity] > 0");

                            t.HasCheckConstraint("CHK_Workspaces_status", "[WorkspaceStatus] BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.Administrators", b =>
                {
                    b.HasBaseType("StudyHubAPI.Models.Entities.Person");

                    b.Property<DateOnly>("HireDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasDefaultValueSql("CAST(GETDATE() AS DATE)");

                    b.ToTable("Administrators", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Person_Role", "[Role] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.Customers", b =>
                {
                    b.HasBaseType("StudyHubAPI.Models.Entities.Person");

                    b.Property<DateOnly>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasDefaultValueSql("CAST(GETDATE() AS DATE)");

                    b.ToTable("Customers", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Person_Role", "[Role] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("StudyHubAPI.Models.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.Reservations", b =>
                {
                    b.HasOne("StudyHubAPI.Models.Entities.Administrators", "Admin")
                        .WithMany("Reservation")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Administrators");

                    b.HasOne("StudyHubAPI.Models.Entities.Customers", "Customer")
                        .WithMany("Reservation")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Customers");

                    b.HasOne("StudyHubAPI.Models.Entities.Workspaces", "Workspace")
                        .WithMany("Reservation")
                        .HasForeignKey("WorkspaceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Workspaces");

                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.Reviews", b =>
                {
                    b.HasOne("StudyHubAPI.Models.Entities.Reservations", "Reservation")
                        .WithMany("Reviews")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Reservations");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.Administrators", b =>
                {
                    b.HasOne("StudyHubAPI.Models.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("StudyHubAPI.Models.Entities.Administrators", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.Customers", b =>
                {
                    b.HasOne("StudyHubAPI.Models.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("StudyHubAPI.Models.Entities.Customers", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.Reservations", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.Workspaces", b =>
                {
                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.Administrators", b =>
                {
                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("StudyHubAPI.Models.Entities.Customers", b =>
                {
                    b.Navigation("Reservation");
                });
#pragma warning restore 612, 618
        }
    }
}
